name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        django-version: ['<2.1', '<2.2', '<3.0', '<3.1', '<3.2', '<3.3', '<4.0']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core
        run: pip install "Django${{ matrix.django-version }}" pydantic pydantic[email]
      - name: Install tests
        run: pip install pytest pytest-django
      - name: Test
        run: pytest
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Black
        run: black --check pydantic_django tests
      - name: isort
        run: isort --check pydantic_django tests
      - name: Flake8
        run: flake8 pydantic_django tests
      - name: mypy
        run: mypy pydantic_django
      - name: Test
        run: pytest --cov=pydantic_django --cov-report=xml tests
      - name: Coverage
        uses: codecov/codecov-action@v3
